require: rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'bin/**/*'
  - 'tmp/**/*'
  - 'db/**/*'
  - 'config/initializers/**/*'
  - 'config/environments/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'app/admin/books.rb'
RSpec/FilePath:
  Enabled: false
RSpec/ExpectActual:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false